package:
  name: nchash
  version: 1.5

source:
  path: ../

requirements:
  build:
    - clang
  host:
    - libarchive
    - openssl
    - libnetcdf
  run:
    - libarchive
    - openssl
    - libnetcdf

